---
- hosts: web
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy hello.txt to server
      copy:
        src: ../hello.txt
        dest: /var/www/html/index.html

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes