name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get instance IP
        id: ip
        run: echo "instance_ip=$(terraform output -raw instance_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

      - name: Add IP to inventory
        run: |
          echo "[web]" > ansible/inventory
          echo "${{ steps.ip.outputs.instance_ip }}" >> ansible/inventory

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/playbook.yml --user ubuntu --private-key key.pem -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'