name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deployment
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Add EC2 host to inventory
        run: |
          echo "[webserver]" > ansible/inventory.ini
          echo "$(terraform -chdir=terraform output -raw public_ip) ansible_user=ubuntu ansible_ssh_private_key_file=ansible/ec2_key.pem" >> ansible/inventory.ini

      - name: Save SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible/ec2_key.pem
          chmod 600 ansible/ec2_key.pem

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
